KWIN_COMPOSE=O2ES
QT_OPENGL=es2
GDK_VULKAN_DISABLE=all
GDK_GL=gles
GST_GL_API=gles2
GST_PLUGIN_PATH_1_0=/usr/share/cix/lib/gstreamer-1.0
LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/cix:/usr/share/cix/lib
CLUTTER_PAINT=disable-clipped-redraws
