Syntax 6

SectionDevice."Speaker" {
	Comment "Speaker"

	EnableSequence [
	]

	DisableSequence [
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
#		PlaybackVolume "PGA1.0 1 Master Playback Volume"
	}
}

SectionDevice."Internal Mic" {
	Comment "Internal Mic"

	EnableSequence [
		cset "name='Int Mic Switch' 1"
		cset "name='Headset Mic Switch' 0"
	]

	DisableSequence [
		cset "name='Int Mic Switch' 0"
		cset "name='Headset Mic Switch' 1"
	]

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},1"
#		CaptureVolume "PGA3.0 3 Master Capture Volume' 50,50"
	}
}

SectionDevice."Headset Mic" {
	Comment "Headset Mic"

	EnableSequence [
		cset "name='Headset Mic Switch' 1"
		cset "name='Int Mic Switch' 0"
	]

	DisableSequence [
		cset "name='Headset Mic Switch' 0"
		cset "name='Int Mic Switch' 1"
	]

	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId},1"
#		CaptureVolume "PGA3.0 3 Master Capture Volume' 50,50"
		JackControl "Headset Mic Jack"
	}
}

SectionDevice."Headset" {
	Comment "Headphone"

	EnableSequence [
		cset "name='Headphone Switch' 1"
	]

	DisableSequence [
		cset "name='Headphone Switch' 0"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},1"
#		PlaybackVolume "PGA2.0 2 Master Playback Volume' 32,32"
		JackControl "Headphone Jack"
	}
}
