#!/bin/sh
set -e

case "$1" in
    configure)
        if [ -x /usr/libexec/cix-grub-config-refresh ]; then
            /usr/libexec/cix-grub-config-refresh || true
        fi
    ;;
esac

#DEBHELPER#

exit 0
