# alc5682 specific boot sequence

BootSequence [
	# headphone
	cset "name='DAC1 MIXL DAC1 Switch' 1"
	cset "name='DAC1 MIXR DAC1 Switch' 1"
	cset "name='Stereo1 DAC MIXL DAC L1 Switch' 1"
	cset "name='Stereo1 DAC MIXR DAC R1 Switch' 1"
	# dmic
	cset "name='RECMIX1L CBJ Switch' 1"
	cset "name='RECMIX1R CBJ Switch' 1"
	cset "name='Stereo1 ADC L1 Mux' 1"
	cset "name='Stereo1 ADC R1 Mux' 1"
	cset "name='Stereo1 ADC MIXL ADC1 Switch' 1"
	cset "name='Stereo1 ADC MIXR ADC1 Switch' 1"
	cset "name='STO1 ADC Boost Gain Volume' 2"
	# headset mic
	cset "name='Stereo1 ADC L2 Mux' 1"
	cset "name='Stereo1 ADC R2 Mux' 1"
	cset "name='Stereo1 ADC MIXL ADC2 Switch' 1"
	cset "name='Stereo1 ADC MIXR ADC2 Switch' 1"
]
