Syntax 6

SectionDevice."Speaker" {
	Comment "Speaker"

	EnableSequence [
		cset "name='Left Spk Switch' 1"
		cset "name='Right Spk Switch' 1"
		cset "name='Headphone Switch' 0"
	]

	DisableSequence [
		cset "name='Left Spk Switch' 0"
		cset "name='Right Spk Switch' 0"
		cset "name='Headphone Switch' 1"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId}"
	}
}

SectionDevice."Internal Mic" {
	Comment "Internal Mic"

	EnableSequence [
		cset "name='Int Mic Switch' 1"
		cset "name='Headset Mic Switch' 0"
	]

	DisableSequence [
		cset "name='Int Mic Switch' 0"
		cset "name='Headset Mic Switch' 1"
	]

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId}"
	}
}

SectionDevice."Headset Mic" {
	Comment "Headset Mic"

	EnableSequence [
		cset "name='Headset Mic Switch' 1"
		cset "name='Int Mic Switch' 0"
	]

	DisableSequence [
		cset "name='Headset Mic Switch' 0"
		cset "name='Int Mic Switch' 1"
	]

	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId}"
		JackControl "Headset Mic Jack"
	}
}

SectionDevice."Headset" {
	Comment "Headphone"

	EnableSequence [
		cset "name='Headphone Switch' 1"
		cset "name='Left Spk Switch' 0"
		cset "name='Right Spk Switch' 0"
	]

	DisableSequence [
		cset "name='Headphone Switch' 0"
		cset "name='Left Spk Switch' 1"
		cset "name='Right Spk Switch' 1"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId}"
		JackControl "Headphone Jack"
	}
}
