Syntax 6

Include.dptx0.File "/CIX/dptx/dptx0.conf"
Include.dptx1.File "/CIX/dptx/dptx1.conf"
Include.dptx2.File "/CIX/dptx/dptx2.conf"
Include.dptx3.File "/CIX/dptx/dptx3.conf"
Include.dptx4.File "/CIX/dptx/dptx4.conf"
