#CIX SKY1 EVB HDA HiFi conf
#
Syntax 6

SectionDevice."Speaker" {
	Comment "Speaker"

	EnableSequence [
		cset "name='Auto-Mute Mode' 0"
		cset "name='Master Playback Switch' 1"
		cset "name='Master Playback Volume' 80%"
		cset "name='Speaker Playback Switch' 1,1"
		cset "name='Speaker Playback Volume' 80%"
		cset "name='Headphone Playback Switch' 0,0"
	]

	DisableSequence [
		cset "name='Speaker Playback Switch' 0,0"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId}"
#		JackControl "Speaker Phantom Jack"
#		PlaybackVolume "name='Master Playback Volume'"
	}
}
SectionDevice."Internal Mic" {
	Comment "Internal Mic"

	EnableSequence [
		cset "name='Capture Source' 0"
		cset "name='Capture Switch' 1,1"
		cset "name='Capture Volume' 80%"
		cset "name='Internal Mic Boost Volume' 2,2"
		cset "name='Mic Boost Volume' 0,0"
	]

	DisableSequence [
		cset "name='Internal Mic Boost Volume' 0,0"
	]


	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId}"
#		JackControl "Internal Mic Phantom Jack"
#		CaptureVolume "name='Capture Volume'"
	}
}

SectionDevice."Headset" {
	Comment "Headphone"

	EnableSequence [
		cset "name='Auto-Mute Mode' 0"
		cset "name='Master Playback Switch' 1"
		cset "name='Master Playback Volume' 80%"
		cset "name='Headphone Playback Switch' 1,1"
		cset "name='Headphone Playback Volume' 80%"
		cset "name='Speaker Playback Switch' 0,0"
	]

	DisableSequence [
		cset "name='Headphone Playback Switch' 0,0"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId}"
		JackControl "Headphone Jack"
#		PlaybackVolume "name='Master Playback Volume'"
	}
}

SectionDevice."Headset Mic" {
	Comment "Headset Mic"

	EnableSequence [
		cset "name='Capture Source' 1"
		cset "name='Capture Switch' 1,1"
		cset "name='Capture Volume' 80%"
		cset "name='Mic Boost Volume' 2,2"
		cset "name='Internal Mic Boost Volume' 0,0"
	]

	DisableSequence [
		cset "name='Mic Boost Volume' 0,0"
	]


	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId}"
		JackControl "Mic Jack"
#		CaptureVolume "name='Capture Volume'"
	}
}
